FROM golang:1.22-bookworm

WORKDIR /app

ADD . /app

RUN make build

ENV PORT=$PORT
ENV SPOTIFY_REFRESH_TOKEN=$SPOTIFY_REFRESH_TOKEN
ENV SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID
ENV SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET

EXPOSE $PORT

CMD ["./bin/main"]